CFC__/Controllers/ContactController.cs
using CFC.Dto;
using NPoco;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace CFC.Controllers
{
    public class ContactController : SurfaceController
    {
        private Database _db;
        public ContactController()
        {
            _db = new Database(ConfigurationManager.ConnectionStrings["cfcFinances"].ConnectionString, ConfigurationManager.ConnectionStrings["cfcFinances"].ProviderName);
        }


        [HttpPost]
       public ActionResult SendMail(FormCollection Form)
        {
            var url = Request.Url.GetLeftPart(UriPartial.Authority);
            try
            {
                Sql sql = new Sql("SELECT * FROM TB_SMTP");
            var ParametreSmtp = _db.Fetch<SmtpDto>(sql).FirstOrDefault();




            string email = Form["email"].ToString();
            string phone = Form["phone"].ToString();
            string objet = Form["objet"].ToString();
            string message = Form["message"].ToString();
            message = message + "\n\n\n" + "Numéro de Téléphone " + phone;

            var client = new SmtpClient() {
                UseDefaultCredentials = false,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                Credentials = new NetworkCredential(ParametreSmtp.NomUtilisateur, ParametreSmtp.Mdp),
                Host =ParametreSmtp.NomServeur,
                Port = Convert.ToInt32(ParametreSmtp.Port),
                EnableSsl = true
            };
            //client.Port = 25;
            //client.Host = "localhost";
            //client.Credentials = new NetworkCredential("user1@test.com", "cedricanselme");
            
            //client.DeliveryMethod = SmtpDeliveryMethod.Network;
            MailMessage mailMessage = new MailMessage(email,ParametreSmtp.NomUtilisateur);
            mailMessage.Subject = objet;
            mailMessage.Body = message;
            
          
                client.Send(mailMessage);
                
                return Redirect(url+"/success");
                

            }
            catch (Exception ex)
            {

                return Redirect(url + "/Echec");
            }

            return null;
        }
    }
}

CFC__/Controllers/RDVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using CFC;
using NPoco;
using System.Configuration;
using CFC.Dto;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Net.Http;
using Newtonsoft.Json.Linq;

namespace CFC.Controllers
{
    public class RDVController : SurfaceController
    {
        private Database _db;
        protected HttpResponseMessage _response = new HttpResponseMessage();
        protected ObjetRetour Result = new ObjetRetour();

        public RDVController()
        {
            _db = new Database(ConfigurationManager.ConnectionStrings["cfcFinances"].ConnectionString, ConfigurationManager.ConnectionStrings["cfcFinances"].ProviderName);
        }



        [HttpPost]
        public JsonResult DemandeRdv(string value)
        {
            var RDV = JsonConvert.DeserializeObject<RdvModel>(value);
            string url = string.Empty;

            try
            {


                var NewEvent = new RdvDto()
                {
                    AnneeConstitution = RDV.AnneeConstitution,
                    ChiffreAffaire = RDV.ChiffreAffaire,
                    DescriptionMotif = RDV.DescriptionMotif,
                    Email = RDV.Email,
                    NomDemandeur = RDV.NomDemandeur,
                    PrenomsDemandeur = RDV.PrenomsDemandeur,
                    Telephone = RDV.Telephone,
                    NomEntreprise = RDV.NomEntreprise,
                    DateRDV = Convert.ToDateTime(RDV.DateRDV),
                    Fonction = RDV.Fonction,
                    ObjetRDV = RDV.ObjetRDV,
                    idSecteur = Convert.ToInt32(RDV.idSecteur),
                    timeRDV = TimeSpan.Parse(RDV.timeRDV),
                    DateCreation = DateTime.UtcNow

                };
                Sql sql = new Sql("SELECT TOP   1 * FROM TB_RDV ORDER BY ROWIDAUTO DESC");
                _db.Insert<RdvDto>("TB_RDV", "RowidAuto", NewEvent);
                var lastRDV = _db.Fetch<RdvDto>(sql).First().RowidAuto;

                foreach (var item in RDV.ListeMotif)
                {
                    var motif = new MotifDto()
                    {
                        idRDV = lastRDV,
                        LibelleMotif = item
                    };
                    _db.Insert<MotifDto>("TB_MOTIF", "ROWIDAUTO", motif);
                }

                url = Request.Url.GetLeftPart(UriPartial.Authority);
                //return Redirect(url + "/success");
                url = url + "/success";
                return Json(new { ok = true, chemin = url }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                url = url + "/Echec";
                return Json(new { ok = true, chemin = url }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpGet]
       public JsonResult ListeRDV()
        {
            Sql sql = new Sql("SELECT NomDemandeur,PrenomsDemandeur,Fonction,Telephone,Email,NomEntreprise,AnneeConstitution,ObjetRDV,ChiffreAffaire,DescriptionMotif,DateRDV,RowidAuto FROM TB_RDV ORDER BY DATECREATION DESC");
            var liste = _db.Fetch<RdvDto>(sql);
            return Json(new { ok = true, liste = liste.ToList() }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult RDVUnique(string id)
        {
            Sql sql = new Sql("SELECT NomDemandeur,PrenomsDemandeur,Fonction,Telephone,Email,NomEntreprise,AnneeConstitution,ObjetRDV,ChiffreAffaire,DescriptionMotif,DateRDV,RowidAuto,idSecteur,DateCreation,timeRDV FROM TB_RDV where rowidauto="+id);
            var liste = _db.Fetch<RdvDto>(sql);
            Sql sqlSecteur = new Sql("SELECT * FROM TB_SECTEUR WHERE ID=" + liste.FirstOrDefault().idSecteur);
            var secteur = _db.Fetch<SecteurDto>(sqlSecteur).FirstOrDefault().LibelleSecteur.ToString();
            Sql sqlMotif = new Sql("SELECT  LibelleMotif from TB_MOTIF WHERE IdRDV="+id);
            var ListeMotif = _db.Fetch<MotifDto>(sqlMotif);
            return Json(new { ok = true, liste = liste.ToList(), ListMotif = ListeMotif, secteur = secteur }, JsonRequestBehavior.AllowGet);
        }



        #region Events / Coaching 
        public async Task<JsonResult> ListeEventsCoaching()
        {
            var liste = await _db.FetchAsync<EventDto>(new Sql().Select("*").From("TB_EVENT"));
            return Json(new { data = liste }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> AjouterEventCoaching(string value)
        {
            try
            {
                if (!string.IsNullOrEmpty(value))
                {
                    var eventCoaching = JsonConvert.DeserializeObject<EventDto>(value);
                    //var date = Convert.ToDateTime(eventCoaching.date);
                    //var time = TimeSpan.Parse(eventCoaching.time);
                    //eventCoaching.DATE_HEURE = date;
                    //eventCoaching.DATE_HEURE.AddHours(time.Hours);
                    //eventCoaching.DATE_HEURE.AddMinutes(time.Minutes);
                    //eventCoaching.DATE_HEURE.AddSeconds(time.Seconds);

                    if (eventCoaching.ROWID == 0)
                    {
                        await _db.InsertAsync<EventDto>("TB_EVENT", "ROWID", true, eventCoaching);
                        return Json(new { data = true }, JsonRequestBehavior.AllowGet);
                    }
                    var ancien = await _db.SingleAsync<EventDto>(new Sql().Select("*").From("TB_EVENT").Where("ROWID = @0", eventCoaching.ROWID));
                    ancien.LIEU = eventCoaching.LIEU;
                    ancien.NOM = eventCoaching.NOM;
                    ancien.TARIF = eventCoaching.TARIF;
                    ancien.TITRE = eventCoaching.TITRE;
                    ancien.TYPE = eventCoaching.TYPE;
                    ancien.URLIMAGE = eventCoaching.URLIMAGE;
                    ancien.DESCRIPTION = eventCoaching.DESCRIPTION;
                    ancien.ESTPAYANT = eventCoaching.ESTPAYANT;
                    ancien.ESTPUBLIER = eventCoaching.ESTPUBLIER;
                    _db.Update("TB_EVENT", "ROWID", ancien);
                    return Json(new { data = true }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { data = false }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { data = false }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public async Task<JsonResult> SupprimerEventCoaching(int ID)
        {
            try
            {
                if (ID > 0)
                {
                    var eventCoaching = await _db.SingleAsync<EventDto>(new Sql().Select("*").From("TB_EVENT").Where("ROWID = @0", ID));
                    _db.Delete("TB_EVENT", "ROWID", eventCoaching);
                    return Json(new { data = true }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { data = false }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { data = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> EventCoaching(int ID)
        {
            try
            {
                if (ID > 0)
                {
                    var eventCoaching = await _db.SingleAsync<EventDto>(new Sql().Select("*").From("TB_EVENT").Where("ROWID = @0", ID));
                    return Json(new { data = eventCoaching }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { data = false }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { data = false }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult Intermediaire()
        {
            return Json(new { data = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListeParticipants(int jsonObject)
        {
            string message = string.Empty;
            try
            {
                //int id = Convert.ToInt32(jsonObject);
                Sql sql = new Sql("SELECT * FROM TB_PARTICPANT TBP, TB_PARTICIPER TBPAR WHERE TBP.ROWID = TBPAR.rowidparticipant AND TBPAR.rowidevenement =" + jsonObject);
                var liste = _db.Fetch<ParticipantDto>(sql);
                return Json(new { ok = true, data = liste }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            return Json(new { ok = false, data = "", message = "Succès" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult VueParticipants(int id)
        {
            TempData["ROWID"] = id;
            var url = Request.Url.GetLeftPart(UriPartial.Authority);
            //tu peux faire passer les parametres ici et les communiquer à la vue soit avec un viewbag ou un viewdata
            return Redirect(url + "/ListeParticipant");
        }

        #endregion


        #region Liste Participant ***by brice***
        [HttpGet]
        public JsonResult ListeParticipants()
        {
            // _db.Fetch<EventDto>(new Sql().Select("*").From("TB_EVENT"));
            //var liste = await _db.FetchAsync<EventDto>(new Sql().Select("*").From("TB_EVENT"));
            try
            {
                var liste = _db.Fetch<ParticipantDto>(new Sql().Select("*").From("TB_PARTICPANT"));
                return Json(new { ok = true, data = liste }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                var message = ex.Message;

CFC__/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Contact>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "Layout_site.cshtml";
}
<div class="btc_tittle_main_wrapper">
    <div class="btc_tittle_img_overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 full_width">
                <div class="btc_tittle_left_heading">
                    <h1>Nous contacter</h1>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 full_width">
                <div class="btc_tittle_right_heading">
                    <div class="btc_tittle_right_cont_wrapper">
                        <ul>
                            <li><a href="Accueil">Accueil</a> <i class="fa fa-angle-right"></i></li>
                            <li>Nous contacter</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="btc_contact_tittle_main_wrapper" data-parallax="scroll" data-image-src="images/content/service_bg.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="btc_contact_tittle_box_wrapper">
                    <div class="btc_step_icon_wrapper">
                        <div class="btc_step_hover_effect">
                            <i class="flaticon-placeholder"></i>
                            <div class="btc_step_overlay"></div>
                        </div>
                    </div>
                    <div class="btc_contact_tittle_contant_wrapper">
                        <h2>Addresse</h2>
                        <p>Abidjan <br /> Cocody, Riviera Palmeraie <br> Boulevard Mitterrand près du nouveau camp militaire d’Akouédo, 3ème étage de l’immeuble SCI PELICAN</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="btc_contact_tittle_box_wrapper btc_contact_tittle_box_wrapper2">
                    <div class="btc_step_icon_wrapper">
                        <div class="btc_step_hover_effect">
                            <i class="flaticon-phone-call"></i>
                            <div class="btc_step_overlay"></div>
                        </div>
                    </div>
                    <div class="btc_contact_tittle_contant_wrapper">
                        <h2>Téléphone</h2>
                        <p>+225 67 604 603 / +225 73 750 000 </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="btc_contact_tittle_box_wrapper btc_contact_tittle_box_wrapper2">
                    <div class="btc_step_icon_wrapper">
                        <div class="btc_step_hover_effect">
                            <i class="flaticon-mail"></i>
                            <div class="btc_step_overlay"></div>
                        </div>
                    </div>
                    <div class="btc_contact_tittle_contant_wrapper">
                        <h2>Email</h2>
                        <p>info@cfcfinance.net</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="btc_contact_map_main_wrapper">
    <div class="btc_contact_map_img_overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="btc_contact_map_left_section">
                    <div id="map" style="width:100%; float:left; height:600px;"></div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="btc_contact_map_right_section">
                    <h5>Get In Touch</h5>
                    <h3>Avez vous des questions ?</h3>
                    <span>#</span>
                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagitti.</p>
                </div>
                @using (Html.BeginForm("SendMail", "Contact",FormMethod.Post))
                {
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="btc_contact_map_inputs">
                            <input type="text" placeholder="Nom" id="nom" name="nom">
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="btc_contact_map_inputs btc_contact_map_inputs3">
                            <input type="email" placeholder="Adresse Email" id="email" name="email">
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="btc_contact_map_inputs btc_contact_map_inputs2">
                            <input type="text" placeholder="Téléphone" id="phone" name="phone">
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="btc_contact_map_inputs btc_contact_map_inputs2">
                            <input type="text" placeholder="Objet du mail" id="objet" name="objet">
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="btc_contact_map_inputs btc_contact_map_inputs2">
                            <textarea rows="6" placeholder="Message" id="message" name="message"></textarea>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="btc_contact_map_btn">
                            <button type="submit">Envoyez</button>

                            @*<ul>
                                <li><a href="#" id="send">Envoyez</a></li>
                                
                            </ul>*@
                        </div>
                    </div>
                </div>
                }


            </div>
        </div>
    </div>
</div>

<script>
    function initMap() {
        var uluru = { lat: 5.3720914935798575, lng: -3.9425025444912034 };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            scrollwheel: false,
            center: uluru
        });
        var marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCqkdlwOxFDpOi-HZmR9yzw-lwWwk_sMVQ&callback=initMap"></script>
<script>
    $(document).ready(function () {

        $("#send").click(function () {
            var ojbet = {
                nom = $("#nom").val(),
                objet = $("#objet").val(),
                message = $("#message").val(),
                phone = $("#phone").val()

            };


        });
    });
</script>

CFC__/Views/Dashboard.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Dashboard>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Layout_app.cshtml";
}

CFC__/Views/FormParticipation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.FormParticipation>
@using ContentModels = Umbraco.Web.PublishedModels;
@using CFC.Dto;
@{
    Layout = "Layout_site.cshtml";

    var ROWID = 0; var NOM = ""; var TITRE = ""; var ESTPAYANT = 0; decimal TARIF = 0;

    var currentEvent = new CurrentEventModel();
    if (Session["CurrentEvent"] != null)
    {
        currentEvent = Session["CurrentEvent"] as CurrentEventModel;
        ROWID = currentEvent.ROWID;
        NOM = currentEvent.NOM;
        TITRE = currentEvent.TITRE;
        ESTPAYANT = currentEvent.ESTPAYANT;
        TARIF = currentEvent.TARIF;
    }
}


<style>
    /* HIDE RADIO */
    [type=radio] {
        position: absolute;
        opacity: 0;
        width: 0;
        height: 0;
    }

        /* IMAGE STYLES */
        [type=radio] + img {
            cursor: pointer;
        }

        /* CHECKED STYLES */
        [type=radio]:checked + img {
            outline: 2px solid #f00;
        }

    label{
        color:black;
        font-size:22px;
    }

    
</style>
<!-- Header Wrapper End -->
<!-- btc tittle Wrapper Start -->
<div class="btc_tittle_main_wrapper">
    <div class="btc_tittle_img_overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-6 col-sm-12 col-xs-12 full_width">
                <div class="btc_tittle_left_heading">
                    <h1>Participer à l'évènement <i style="color:#ff880e;"> @NOM</i> </h1>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- btc tittle Wrapper End -->
<!-- btc calcultor Wrapper Start -->
<div class="btc_calc_main_wrapper1">
    <div class="btc_calc_img_overlay"></div>
    <div class="container">
        
        <div class="row">
            
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br />
                <br />
                <div class="col-lg-6">
                    <div class="">
                        <div class="cal-convertor">

                            <div class="form-group">

                                <label class="control-label"> Nom et prénoms</label>
                                <input type="text" id="nomprenoms" name="nomprenoms" class="form-control">

                            </div>
                            <div class="form-group">

                                <label class="control-label"> Titre/ Fonction</label>
                                <input type="text" id="fonction" name="fonction" class="form-control">
                            </div>
                            <div class="form-group">

                                <label class="control-label"> Téléphone</label>
                                <input type="tel" id="telephone" name="telephone" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="control-label"> Email</label>
                                <input type="email" id="email" name="email" class="form-control">
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="">
                        <div class="cal-convertor">
                            <div class="cal-convertor">
                                <div class="form-group">

                                    <label class="control-label"> Nom Entreprise</label>
                                    <input type="text" id="nomentreprise" name="nomentreprise" class="form-control">

                                </div>
                                <div class="form-group">

                                    <label class="control-label"> Année constitution</label>
                                    <input type="text" id="anneeconstitution" name="anneeconstitution" class="form-control">
                                </div>
                                <div class="form-group">

                                    <label class="control-label"> Secteur d'activité</label>
                                    @*<input type="tel" id="secteuractivite" name="secteuractivite" class="form-control">*@
                                    <select class=" form-control" id="secteuractivite">
                                        <option selected disabled>--Secteur d'activité--</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="control-label"> Adresse géographique</label>
                                    <input type="email" id="adresse" name="adresse" class="form-control">
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- btc calcultor Wrapper End -->
<!-- btc Video Wrapper Start -->
@{
    if (ESTPAYANT == 1)
    {
        <div class="row" style="height:-5%;">
            <div class="">
                <div class="">
                    <br />
                    <h1 class="text-center">UTILISER LES MOYENS DE PAIEMENTS ELECTRONIQUE POUR RESERVER VOTRE PLACE</h1>
                    <br />
                    <div class="row text-center">
                        <label>
                            <input type="radio" id="Orange" name="test" value="1" checked>
                            <img src="~/assets/images/omoney_logo.png">
                        </label>

                        <label>
                            <input type="radio" id="Moov" name="test" value="2">
                            <img src="~/assets/images/moovmoney.png">
                        </label>
                    </div>
                </div>

            </div>
        </div>
    }
}

<div class="btc_video_main_wrapper">
    <div class="container">

        <div class="row btc_video_center_wrapper text-center">
            <button class="btn btn-lg" onclick="btnsubmit()">RESERVER MA PLACE</button>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticPaiement" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <input type="hidden" id="OrderId" />
        <div class="modal-content">
            <iframe class="modal-body col-lg-12" id="iframePaiement"
                    title="Paiement Mobile"
                    @*width="500"*@
                    height="550"
                    src="https://webpayment.orange-money.com/ci/mpayment/abstract/v1dmkzexdbjhsdflnjxs2wvd8vrnfeqaplfy10gidicvnrbev14zeid1nfnyyxzr"></iframe>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger" onclick="btnFermer()">Fermer</button>
            </div>
        </div>
    </div>
</div>

<script src="~/assets/adminAssets/js/jquery-3.2.1.min.js"></script>
<script src="~/assets/adminAssets/sweet-alert2/sweetalert2.all.js"></script>
<script src="~/assets/adminAssets/sweet-alert2/sweetalert2.min.js"></script>
<script>
    $(document).ready(function () {
        GetAllSecteurActivite();
    });
    //Get all Secteur Activite
    function GetAllSecteurActivite() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("ListeSecteurActivite", "RDV")',
            success: function (data) {
                $.each(data.data, function (i, val) {
                    var line = '<option value=' + val.ID + '>' + val.LibelleSecteur + '</option>'
                    $("#secteuractivite").append(line);
                });
            }

        });
    }


    $('#Moov').click(function () {
        if ($('#Orange').is(':checked') == true) {
            $(':checkbox#Orange').prop('checked', false);
        }
    });
    $('#Orange').click(function () {
        if ($('#Moov').is(':checked') == true) {
            $(':checkbox#Moov').prop('checked', false);
        }
    });


    //fonction pour ajouter un element construit par objet
    function btnsubmit() {
        var checkOperateur = 0;
        $('input[type="radio"]:checked').each(function (i) {
            checkOperateur = $(this).val();
        });

        //alert(checkOperateur);
        //debugger;
        @*var resp = VerifInput();
        if (resp.succes == true && '@ROWID' != "") {
            $("#Valider").html('<i class="fas fa-circle-notch fa-spin" aria-hidden="true"></i> Validation...');*@
            var operation = {
                NomPrenoms: $("#nomprenoms").val(),
                Titre: $("#fonction").val(),
                Telephone: $("#telephone").val(),
                email: $("#email").val(),

                NomEts: $("#nomentreprise").val(),
                AnneeConstitution: $("#anneeconstitution").val(),
                Id_Secteur: $("#secteuractivite").val(),
                Adressegeographique: $("#adresse").val()
            };

            //alert(JSON.stringify(operation));
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddParticipant", "RDV")',
                data: { jsonObject: JSON.stringify(operation), Operateur: checkOperateur},
                dataType: "json",
                success: function (data) {
                    if (data.ok == true) {
                        if (data.aPayer == 1) {
                            $("#OrderId").val(data.data.orderId);
                            $('#iframePaiement').attr('src', data.data.payment_url);

                            $("#Payer").html('Payer');
                            $("#staticPaiement").modal("show");
                        } else {
                            swal("Succès", data.message, "success").then(function (result) {
                                window.location.href = "/Accueil";
                            });
                        }
                    }
                    else {
                        $("#Payer").html('Payer');
                        swal("Attention", data.message, "error");
                    }
                },
                error: function (msg) {
                    $("#Valider").html('Valider');
                    swal("Ooups!!!", "code erreur 404 ", "error");

                }

            });
        //}
    }

    function btnFermer() {
        //$("#staticPaiement").modal("hide");
        var checkOperateur = 0;
        $('input[type="radio"]:checked').each(function (i) {
            checkOperateur = $(this).val();
        });

        if (checkOperateur != 0) {
            var operation = {
                operateur: checkOperateur,
                OrderId: $("#OrderId").val()
            };

            //alert(JSON.stringify(operation));
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetStatutPaiement", "RDV")',
                data: { jsonObject: JSON.stringify(operation) },
                dataType: "json",
                success: function (data) {
                    if (data.ok == true) {
                        swal("Succès", data.message, "success").then(function (result) {
                            $("#staticPaiement").modal("hide");
                            window.location.href = "/Accueil";
                        });
                    } else {
                        swal("Echec", data.message, "warning").then(function (result) {
                            $("#staticPaiement").modal("hide");
                            window.location.href = "/Accueil";
                        });
                    }
                },
                error: function (msg) {

                    swal("Ooups!!!", "code erreur 404.", "error");

                }

            });
        } else {
            swal("Attention !", "Précisez l'opérateur svp.", "warning");
        }

    }
</script>